Application Internal Error - C:\Program Files (x86)\TPuy\bin\tpuy_win_x86_hb32.exe
Terminated at: 2025-03-31 21:10:54
Error irrecuperable 9001: Fallo en recuperaci¢n de error
Called from NETIO_FUNCEXEC(0)
Called from FROMREMOTE(534) in ./src/main.prg
Called from ROBJECT:GET(164) in ./src/rclasses.prg
Called from ROBJECT:MODULO(131) in ./src/rclasses.prg
Called from (b)GEMPRESA(80) in pcode.hrb
Called from GEMPRESA:SETMODULO(0) in pcode.hrb
Called from (b)EVAL(13)
Called from TSCRIPT:RUN(257) in ./src/tscript.prg
Called from TAPP:RUNXBS(215) in ./src/tapp.prg
Called from (b)EVAL(114)
Called from GMENUITEM:ONACTIVATE(100) in gobject.prg
Called from GTK_MAIN(0)
Called from GWINDOW:ACTIVATE(167) in gwindow.prg
Called from TPYWINDOW:ACTIVATE(97) in ./src/tpywindow.prg
Called from (b)EVAL(161)
Called from TSCRIPT:RUN(257) in ./src/tscript.prg
Called from TAPP:RUNXBS(215) in ./src/tapp.prg
Called from LOGIN_RUN(129) in pcode.hrb
Called from (b)EVAL(52)
Called from GBUTTON:ONCLICKED(151) in gbutton.prg
Called from GTK_MAIN(0)
Called from GWINDOW:ACTIVATE(167) in gwindow.prg
Called from TPYWINDOW:ACTIVATE(97) in ./src/tpywindow.prg
Called from (b)EVAL(77)
Called from TSCRIPT:RUN(257) in ./src/tscript.prg
Called from TAPP:RUNXBS(215) in ./src/tapp.prg
Called from __LOGIN(99) in pcode.hrb
Called from (b)EVAL(41)
Called from TSCRIPT:RUN(257) in ./src/tscript.prg
Called from TAPP:RUNXBS(215) in ./src/tapp.prg
Called from (b)EVAL(25)
Called from TSCRIPT:RUN(257) in ./src/tscript.prg
Called from TAPP:RUNXBS(215) in ./src/tapp.prg
Called from MAIN(273) in ./src/main.prg
------------------------------------------------------------------------
